hangman/config/routes.rb
Rails.application.routes.draw do

  resources :games do
    resources :guesses, only: [:create]
  end

  root 'games#index'
end

hangman/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hangman/app/models/game.rb
class Game < ApplicationRecord
  ONLY_ALPHABETIC = "is only allowed to contain alphabetic characters [s,w,g NOT @,*,4]"
  UNCHANGEABLE_AFTER_GUESS_MADE = "in unable to be changed once a Guess has been made"

  has_many :guesses, dependent: :destroy

  validate :has_not_begun?

  validates_presence_of :secret_word
  validates_length_of :secret_word, :minimum => 3
  validates_format_of :secret_word, :with => /\A[a-z]+\z/i, message: ONLY_ALPHABETIC

  before_save :downcase_secret_word!

  def guessed_letters
    guesses.pluck(:letter)
  end

  def lives
    secret_letters.size - incorrect_guesses.size
  end

  def secret_letters
    secret_word.chars
  end

  def incorrect_guesses
    guessed_letters - secret_letters
  end

  def finished?
    won? || lost?
  end

  def won?
    all_letters_guessed? && lives > 0
  end

  def lost?
    lives <= 0
  end

  private

  def all_letters_guessed?
    (secret_letters - guessed_letters).empty?
  end

  def has_not_begun?
    errors.add(:game, UNCHANGEABLE_AFTER_GUESS_MADE) unless guesses.empty?
  end

  def downcase_secret_word!
     self.secret_word.downcase!
  end
end

hangman/app/models/guess.rb
class Guess < ApplicationRecord
  ONLY_ALPHABETIC = "is only allowed to contain alphabetic characters [s,w,g NOT @,*,4]"
  REPEATED_GUESS = "has already been guessed"

  belongs_to :game

  validates_presence_of :letter
  validates_length_of :letter, :maximum => 1
  validates_format_of :letter, :with => /\A[a-z]+\z/i, message: ONLY_ALPHABETIC
  validates_uniqueness_of :letter, scope: :game, message: REPEATED_GUESS

  before_save :downcase_letter!

  private

  def downcase_letter!
    self.letter.downcase!
  end
end

hangman/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

hangman/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game
    else
      render 'new'
    end
  end

  def update
    if @game.update(game_params)
      redirect_to @game
    else
      render 'edit'
    end
  end

  def destroy
    @game.destroy

    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:secret_word)
  end

  def find_game
    @game ||= Game.find(params[:id])
  end
end

hangman/app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  def create
    game = Game.find(params[:game_id])
    guess = game.guesses.new(guess_params)

    flash[:error] = guess.errors.full_messages unless guess.save

    redirect_to game
  end

  private

  def guess_params
    params.require(:guess).permit(:letter)
  end
end

hangman/app/helpers/application_helper.rb
module ApplicationHelper
end

hangman/app/helpers/games_helper.rb
module GamesHelper
  NO_GUESS_MADE = 'no guesses made'
  WON = 'You WON!'
  LOST = 'You LOST!'
  MASK = '_'

  def masked_letters(secret_letters, guessed_letters)
    secret_letters.map { |letter| guessed_letters.include?(letter) ? letter : MASK }.join(' ')
  end

  def gameover_message(won)
    won ? WON : LOST
  end
end

hangman/app/views/games/_error.html.erb
<% if @game.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@game.errors.count, "error") %> prohibited
      this game from being saved:
    </h2>
    <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

hangman/app/views/games/_flash.html.erb
<% if flash[:error] %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(flash[:error].count, "error") %> prohibited this entry:
    </h4>
    <ul>
      <% flash[:error].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

hangman/app/views/games/_form.html.erb
<%= form_with(model: @game, local: true) do |form| %>
  <%= render 'error' %>

  <p>
    <%= form.label :secret_word %><br>
    <%= form.text_field :secret_word, autofocus: true %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

hangman/app/views/games/_game_information.html.erb
<h2>Game Information:</h2>

<p>
  <strong>Masked Letters:</strong>
  <%= masked_letters(@game.secret_word.chars, @game.guessed_letters) %>
</p>

<p>
  <strong>Word Length:</strong>
  <%= @game.secret_word.length %>
</p>

<p>
  <strong>Remaining Lives:</strong>
  <%= @game.lives %>
</p>

<p>
  <strong>Guessed Letters:</strong>
  <% if @game.guessed_letters.any? %>
    <%= @game.guessed_letters.join(' ') %>
  <% else %>
    No guesses have been made
  <% end %>
</p>

hangman/app/views/games/_game_result.html.erb
<h2>Game Results:</h2>

<p>
  <strong><%= gameover_message(@game.won?) %></strong>
</p>

<p>
  <strong>The word was:</strong>
  <%= @game.secret_word %>
</p>

hangman/app/views/games/_make_guess.html.erb
<h2>Make a Guess:</h2>

<%= form_with(model: [ @game, @game.guesses.build ], local: true) do |form| %>
  <%= render 'flash' %>
  
  <p>
    <%= form.label :letter %>
    <%= form.text_field :letter, autofocus: true %>
    <%= form.submit %>
  </p>
<% end %>

hangman/app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

hangman/app/views/games/index.html.erb
<h1>Listing Games</h1>

<%= link_to 'New Game', new_game_path %>

<table>
  <tr>
    <th>Secret Word</th>
    <th colspan="3"></th>
  </tr>

  <% @games.each do |game| %>
    <tr>
      <td><%= game.secret_word %></td>
      <td><%= link_to 'Show', game_path(game) %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game_path(game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

hangman/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

hangman/app/views/games/show.html.erb
<h1>Hangman</h1>

<%= render 'game_information' %>

<% if @game.finished? %>
  <%= render 'game_result' %>
<% else %>
  <%= render 'make_guess' %>
<% end %>

<%= link_to 'Edit', edit_game_path(@game) %>
<%= link_to 'Back', games_path %>

<p>
  <strong>Remove after testing:</strong>
  <%= @game.secret_word %>
</p>

hangman/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>